import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Container, Row, Col } from "react-bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-calendar/dist/Calendar.css";
import Script from 'next/script'

import Calendar from "react-calendar/dist/umd/Calendar";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web Listed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
          rel="stylesheet"
          
        />
       
      </Head>
      <div className="container-fluid">
      <nav className="navbar navbar-expand-lg back_1 ">
  <div className="container-fluid">
    <a className="navbar-brand" href="#"><img src="https://painting.demoapp-lc.com/wp-content/uploads/2022/05/weblisted-01.png" alt=""className="img_logo" / ></a>
    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span className="navbar-toggler-icon"></span>
    </button>
     <Row>Name
         <Col sm="3">
         
  <select name="cars" id="cars">
    <option value="volvo">dallar</option>
    <option value="saab">Saab</option>
    <option value="opel">Opel</option>
    <option value="audi">Audi</option>
  </select>
 
         </Col>
         <Col sm="4">  
        
  <select name="cars" id="cars">
    <option value="volvo">all dallar</option>
    <option value="saab">Saab</option>
    <option value="opel">Opel</option>
    <option value="audi">Audi</option>
  </select>
  
         </Col>
         <Col sm="4">
       
  <select name="cars" id="cars">
    <option value="volvo">Jobs</option>
    <option value="saab">Saab</option>
    <option value="opel">Opel</option>
    <option value="audi">Audi</option>
  </select>
  
         </Col>
     </Row>
    <div className="collapse navbar-collapse" id="navbarSupportedContent">
      <ul className="navbar-nav ml-auto mb-2 mb-lg-0">
        <li className="nav-item">
          <a className="nav-link active" aria-current="page" href="#">Post</a>
        </li>
        <li className="nav-item">
          <a className="nav-link active" href="#">I</a>
        </li>
        
        <li className="nav-item">
          <a className="nav-link active" href="#"  aria-disabled="true">Account</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>

</div>
</div>

      );
      }
