/* eslint-disable react-hooks/rules-of-hooks */
import React,{useState, useEffect} from 'react'
import "bootstrap/dist/css/bootstrap.min.css";
import OrderList from '../components/component/OrderList'
import Head from 'next/head';
import styles from '../styles/Order.module.css'


export default function Order ({orders}) {
    
    return (
        <>
        <Head>
        <title>FoodPort</title>
        <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/icon-06.png" /> 
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
    </Head>


        <main>
            <div className="container" id={styles.order_main}>
            
                <div className="row">
                    <div className="col-md-2"></div>
                    <div className="col-md-12 col-lg-8 col-sm-12" id={styles.orders}>
                    <h3>Orders</h3>
                        <div className={styles.orders_span}></div>
                      
                      
                    </div>
                    <div className="col-md-2"></div>
                  <OrderList />
                    
                </div>
            </div>
            </main>
        </>
    )
}
